[package]
name = "this-week-in-rust-search"
version = "0.1.0"
authors = ["Petr Kosikhin <petr.kosikhin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = "0.7.0"
